package com.suyog.spring.constants;

public interface QueryConstants {
String	ACCOUNT_SAVE = "INSERT INTO ACCOUNT VALUES(?,?,?)";
String  ACCOUNT_UPDATE = "UPDATE ACCOUNT SET NAME = ?, BALANCE = ?, BALANCE = ?, WHERE ACCNO = ?";
String  ACCOUNT_DELETE_BY_ACCNO = " DELETE FROM ACCOUNT WHERE ACCNO = ?";
String  ACCOUNT_FIND_BY_ACCNO = "SELECT * FROM ACCOUNT WHERE ACCNO = ?";
String  ACCOUNT_FIND_BY_NAME = "SELECT * FROM ACCOUNT WHERE NAME = ?";
String  ACCOUNT_FIND_BY_BALANCE = "SELECT * FROM ACCOUNT WHERE BALANCE = ?";
String  ACCOUNT_FIND_ALL = "SELECT * FROM ACCOUNT";
String  ACCOUNT_ROW_COUNT = "SELECT COUNT(*) FROM ACCOUNT";
}
